server:
  port: 443
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE_PATH}  # Let's Encrypt에서 발급받은 인증서의 전체 경로
    key-store-password: ${SSL_KEY_STORE_PASSWORD}  # Let's Encrypt에서는 비밀번호를 사용하지 않습니다.
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ward_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
