name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.5'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start..."
          while ! nc -z localhost 3306; do   
            sleep 1
          done

      - name: Build with Gradle
        env:
          DB_URL: jdbc:mysql://localhost:3306/${{ secrets.MYSQL_DATABASE }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
          DB_USERNAME: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_PASSWORD: ${{ secrets.JWT_PASSWORD }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SSL_ENABLED: ${{ secrets.SSL_ENABLED }}
          SSL_KEY_STORE_PATH: ${{ secrets.SSL_KEY_STORE_PATH }}
          SSL_KEY_STORE_PASSWORD: ${{ secrets.SSL_KEY_STORE_PASSWORD }}
          KAKAO_SERVICE_APP_ADMIN_KEY: ${{ secrets.KAKAO_SERVICE_APP_ADMIN_KEY }}
          APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_PRIVATE_KEY: ${{ secrets.APPLE_PRIVATE_KEY }}
          CHROME_DRIVER_PATH: ${{ secrets.CHROME_DRIVER_PATH }}
        run: ./gradlew build --stacktrace --info

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: build/libs/ward_server-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "ward_server-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"

      - name: Restart application on EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl disable ward_server
            sudo systemctl stop ward_server
            sudo systemctl enable ward_server
            sudo systemctl start ward_server
